### ISSUE TITLE
[Débito Técnico] Acrescentar data de início do curso

### ISSUE THREAD

**Issue by danitamazato** [c137santos/FATEC-API-1-SEMESTRE#146]
Em duas telas, devemos acrescentar a data de início do curso.

Segue um exemplo de tela.

![Image](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/143049584/78b4220b-2415-41f5-acda-eb70f1ac6432)

**Comment by RuthMira** [comment]
oi

**Comment by caiopalma** [comment]
Vou fazer essa!
