### ISSUE TITLE
Apresentação Final

### ISSUE THREAD

**Issue by RuthMira** [c137santos/FATEC-API-1-SEMESTRE#237]
Validar o que deve ser apresentado com cliente

Caso seja os processos , podemos usar o ppt anterior.
Caso seja o produto , gravar tela realizando todo o processo.

**Comment by sararobertnahra** [comment]
Aqui!

**Comment by danitamazato** [comment]
Validação da apresentação com o Cliente:
"Não há necessidade de apresentar todo o produto, uma vez que 4 minutos não é suficiente. Sintetizem rapidamente o que já foi entregue (oral) e foquem no incremento de produto da Sprint 4. Caso algo deixe de ser implementado ou alguma oportunidade de melhoria fique de fora cite como trabalhos futuros"
