### ISSUE TITLE
Exportação de dados: Como um administrador, eu quero selecionar as opções de gerenciamento e relatórios. Isso envolve a exportação de dados.

### ISSUE THREAD

**Issue by marilia-borgo** [c137santos/FATEC-API-1-SEMESTRE#28]
frontend:
- Botão no Index.html que gere relatórios vindo dos: gerenciamento_turmas.html, gerenciamento_alunos.html,gerenciamento_ciclos.html, gerenciamento_global.html.

backend: 
- Rota da APi:/api/relatorio/criar: Consolida os dados e exporta em formato PDF.
- Consolida os dados e os exporta em formato PDF.

Regra de Négocio:
- [ ] * definir planilha padrão
- [ ] * tela 1: selecionar turma para iniciar a exportação de dados em csv

Front-end:
Exportaçao_dados.html - listar todas as informações seguindo o modelo de Excel (tabela de dados.

Back-end:
rota das informações que estão na tabela modelo.

https://docs.google.com/spreadsheets/d/10QrhPG3bGvjZGEObrseubNoIRyDGoVRpuz9bfBSQFjc/edit#gid=1484652080

![epic1-hist1](https://github.com/ClaraSantosmf/FATEC-API-1-SEMESTRE/assets/143049584/3765d87f-78a6-48fc-a15d-f7a72c287127)

**Comment by danitamazato** [comment]
Regra de Négocio:
- [ ] * definir planilha padrão
- [ ] * tela 1: selecionar turma para iniciar a exportação de dados em csv

Front-end:
Exportaçao_dados.html - listar todas as informações seguindo o modelo de Excel (tabela de dados.

Back-end:
rota das informações que estão na tabela modelo.
